name: Desplegando en nginx ec2
on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.10.0

     - name: Set up AWS CLI
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

     - name: Create .env file
       run: |
         echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
         
     - name: Initialize Terraform
       run: terraform init
 
     - name: Terraform Plan
       run: terraform plan -destroy
 
     - name: Apply Terraform changes
       run: terraform apply -auto-approve